#!/bin/bash
set -e

PREFIX=$(date "+%Y%m%d%H%M%S")
VM_NAME=$PREFIX-vm
SUBSCRIPTION_ID="0bf5bc92-8ea2-4160-a704-7130857f3ba3"

# resourcegroup: vpnp2s
# vnet: VNet
# subnet: vmSubnet
# location: japaneast
# vmimage: DS2 v2: 2 vCPU、7 GB の RAM、14 GB の一時ストレージ, $0.140/時間

# check az command
if [ -z "$(which az)" ]; then
  echo "az command not found. Please install Azure CLI."
  exit 1
fi

az login
az account set --subscription $SUBSCRIPTION_ID

echo "az vm create \
  --resource-group vpnp2s \
  --location japaneast \
  --name $VM_NAME \
  --image Ubuntu2204 \
  --size Standard_DS2_v2 \
  --storage-sku Premium_LRS \
  --data-disk-sizes-gb 128 \
  --vnet-name VNet \
  --custom-data cloud-init.cfg \
  --generate-ssh-keys \
  --priority Spot \
  --max-price -1 \
  --eviction-policy Deallocate \
  --subnet vmSubnet \
  --public-ip-address \"\""

az vm create \
  --resource-group vpnp2s \
  --location japaneast \
  --name $VM_NAME \
  --image Ubuntu2204 \
  --size Standard_DS2_v2 \
  --storage-sku Premium_LRS \
  --data-disk-sizes-gb 128 \
  --vnet-name VNet \
  --custom-data cloud-init.cfg \
  --generate-ssh-keys \
  --priority Spot \
  --max-price -1 \
  --eviction-policy Deallocate \
  --subnet vmSubnet \
  --public-ip-address ""

echo ""
echo "Complated!"
echo ""
echo "----------------------------------------------------------------"
echo "# How to login to VM"
echo ""
echo "Run Azure VPN Client and connect to VPN."
echo "ssh koudaiii@$(az vm show -n $VM_NAME -g vpnp2s --show-details -o json --query privateIps -o tsv)"
echo ""
