---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: autoclean=yes
    - apt: update_cache=yes
    - apt: upgrade=dist
    - apt: name=build-essential state=present
    - apt: name=git state=present
    - apt: name=gcc state=present
    - apt: name=patch state=present
    - apt: name=autoconf state=present
    - apt: name=automake state=present
    - apt: name=bison state=present
    - apt: name=libssl-dev state=present
    - apt: name=libyaml-dev state=present
    - apt: name=libreadline6-dev state=present
    - apt: name=zlib1g-dev state=present
    - apt: name=libncurses5-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=libgdbm6 state=present
    - apt: name=libgdbm-dev state=present
    - apt: name=libmysqlclient-dev state=present
    - apt: name=libpq-dev state=present
    - apt: name=libcurl4-openssl-dev state=present
    - apt: name=libpng16-16
    - apt: name=libpng-dev state=present
    - apt: name=libmcrypt4 state=present
    - apt: name=libmcrypt-dev state=present
    - apt: name=libtidy5deb1 state=present
    - apt: name=libtidy-dev state=present
    - apt: name=libxml2-dev state=present
    - apt: name=libxslt1-dev state=present
    - apt: name=readline-common state=present
    - apt: name=curl state=present
    - apt: name=pkg-config
    - apt: name=acl
    - apt: name=docker-ce
    - apt: name=docker-ce-cli
    - apt: name=containerd.io
    - apt: name=docker-buildx-plugin
    - apt: name=docker-compose-plugin
---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce and docker-compose
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
