- hosts: guests:extras
  become: yes
  become_user: koudaiii
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/koudaiii/.xbuild
        update=yes
    # ruby
    # datasource=ruby-version depName=ruby
    - command: /home/koudaiii/.xbuild/ruby-install 3.2.2 /home/koudaiii/.local/ruby
      args:
        creates: /home/koudaiii/.local/ruby/bin/ruby
    # golang
    # datasource=golang-version depName=golang
    - shell: /home/koudaiii/.xbuild/go-install 1.21.1 /home/koudaiii/.local/go $(uname -s | tr [A-Z] [a-z]) $(dpkg --print-architecture)
      args:
        creates: /home/koudaiii/.local/go/bin/go
    # python
    # datasource=python-version depName=python
    - shell: /home/koudaiii/.xbuild/python-install 3.9.7 /home/koudaiii/.local/python $(uname -s | tr [A-Z] [a-z]) $(dpkg --print-architecture)
      args:
        creates: /home/koudaiii/.local/python/bin/python
