#!/bin/bash
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

export PATH=/usr/local/bin:$PATH
export PATH=/home/koudaiii/.local/ruby/bin:$PATH
export PATH=/home/koudaiii/.local/go/bin:$PATH
export PATH=/home/koudaiii/.local/python/bin:$PATH
